### ISSUE TITLE
Fireworks 2.0

### ISSUE THREAD

**Issue by jackrugile** [KingPixil/Main180#8]
Wow, just wanted to say that you did an amazing job with this code. Your critical thinking here made such a beautiful result.

What was your inspiration for this type of demo?

https://180projectblog.wordpress.com/2016/01/24/fireworks-2-0/

**Comment by kbrsh** [comment]
My inspiration was from you! I loved your tutorial on thecodeplayer, and that really helped me understand EXACTLY what was happening.

**Comment by jackrugile** [comment]
Awesome, thanks!

**Comment by kbrsh** [comment]
I love your canvas demos, you really are a master, I am more of a...newbie.
Is there any chance you can, show me the ropes of canvas? It would be really awesome :smile:
